version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: staging/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=http://supabase:${SUPABASE_PORT:-54321}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_TEST_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_TEST_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - supabase
    networks:
      - genia-network

  backend:
    build:
      context: ../backend
      dockerfile: ../staging/Dockerfile.backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - ENVIRONMENT=staging
      - SUPABASE_URL=http://supabase:${SUPABASE_PORT:-54321}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../backend:/app
    depends_on:
      - supabase
    networks:
      - genia-network

  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "${SUPABASE_PORT:-54321}:54321"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ../supabase/migrations:/supabase/migrations
      - supabase-data:/var/lib/postgresql/data
    networks:
      - genia-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
      - supabase
    networks:
      - genia-network

  # Servicio para monitoreo
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - genia-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - genia-network

  # Servicio para pruebas de carga
  k6:
    image: loadimpact/k6:latest
    volumes:
      - ./k6:/scripts
    networks:
      - genia-network

networks:
  genia-network:
    driver: bridge

volumes:
  supabase-data:
  grafana-data:
